import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/app";

import { Geist, Geist_Mono, Alegreya_SC, Dosis } from "next/font/google";
import { cn } from "@/utils/cn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alegryaSc = Alegreya_SC({
  variable: "--font-alegrya-sc",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
});

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head> */}
      <body
        className={cn(
          ` bg-background font-info dark text-foreground relative flex flex-col w-screen max-w-screen overflow-x-hidden`,
          geistSans.variable,
          geistMono.variable,
          alegryaSc.variable,
          dosis.variable
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
