import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/app";

import { Geist, Geist_Mono, Alegreya_SC, Dosis } from "next/font/google";
import { cn } from "@/utils/cn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alegryaSc = Alegreya_SC({
  variable: "--font-alegrya-sc",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
});

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          ` bg-background font-info dark text-foreground w-full p-0 m-0 relative flex flex-col `,
          geistSans.variable,
          geistMono.variable,
          alegryaSc.variable,
          dosis.variable
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
